FROM nginx:alpine

#COPY .infrastructure/nginx.conf /etc/nginx/nginx.conf
    #build:
    #  context: ../
    #  dockerfile: .infrastructure/docker/nginx/Dockerfile.local

#COPY ./public /var/www/public

EXPOSE 80
