services:
  php:
    image: php:8.2-fpm
    build:
      context: ../
      dockerfile: .infrastructure/docker/php/Dockerfile.local
    container_name: php-container-local
    volumes:
      - ../:/var/www/html
      - /var/www/html/.infrastructure/.db
    working_dir: /var/www/html
    ports:
      - "9000:9000"
    networks:
      - symfony_net
    environment:
      - APP_ENV=dev
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: nginx-container-local
    volumes:
      - ../:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "7766:80"
    networks:
      - symfony_net
    depends_on:
      - php

  mysql:
    image: mysql:8.3
    container_name: mysql-container-local
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_USER_PASSWORD}
      MYSQL_USER: ${MYSQL_USER_NAME}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
    volumes:
      - .db:/var/lib/mysql
    ports:
      - "3316:3306"
    networks:
      - symfony_net
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  symfony_net:
    driver: bridge
